# Base configs
baseurl: ""
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Astrophotography by Alexander Eggers"
subtitle: ""
author: "Alexander Eggers"
header:
 title: "Astrophotography"
 subtitle: "by Alexander Eggers"
footer:
 name: "Hi, I'm Alexander"
 bio: "I'm a robotics engineer from Texas. I take pictures of space in my spare time."
# Tag is the actual metadata tag, icon is a fontawesome icon. Use JSON notation without line breaks
img_meta: '[{"tag": "sensor", "icon": "camera-retro"}, {"tag": "scope", "icon": "telescope"}, {"tag": "focallength", "icon": "ruler-horizontal"}, {"tag": "fratio", "icon": "dot-circle-o"}]'
social_urls:
  instagram: "https://www.instagram.com/apeggers"
  github: "https://www.github.com/apeggers"
